/*
Conekta API

Testing TokensApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package conekta_test

import (
	"context"
	"net/http"
	"testing"

	"github.com/conekta/conekta-go"
)

func Test_conekta_TokensApiService(t *testing.T) {

	configuration := conekta.NewConfiguration()
	configuration.Host = _basePath
	configuration.Scheme = "http"
	apiClient := conekta.NewAPIClient(configuration)

	t.Run("Test TokensApiService CreateToken", func(t *testing.T) {
		req := conekta.Token{
			Card: *conekta.NewNullableTokenCard(conekta.NewTokenCard("123", "02", "27", "Foo Foo", "5475040095304607")),
		}
		resp, httpRes, err := apiClient.TokensApi.CreateToken(context.TODO()).
			Token(req).
			AcceptLanguage("es").
			Execute()

		if err != nil {
			t.Fatalf("expected err nil but was %v", err)
		}
		if resp == nil {
			t.Fatalf("expected resp not nil but was %v", resp)
		}
		if httpRes.StatusCode != http.StatusOK {
			t.Fatalf("expected StatusCode 200 OK but was %d", httpRes.StatusCode)
		}

	})

}
