/*
Conekta API

Conekta sdk

API version: 2.1.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the GetPaymentMethodResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPaymentMethodResponse{}

// GetPaymentMethodResponse struct for GetPaymentMethodResponse
type GetPaymentMethodResponse struct {
	Object string `json:"object"`
	HasMore bool `json:"has_more"`
	// URL of the next page.
	NextPageUrl NullableString `json:"next_page_url,omitempty"`
	// Url of the previous page.
	PreviousPageUrl NullableString `json:"previous_page_url,omitempty"`
	Data []GetCustomerPaymentMethodDataResponse `json:"data,omitempty"`
}

// NewGetPaymentMethodResponse instantiates a new GetPaymentMethodResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPaymentMethodResponse(object string, hasMore bool) *GetPaymentMethodResponse {
	this := GetPaymentMethodResponse{}
	this.Object = object
	this.HasMore = hasMore
	return &this
}

// NewGetPaymentMethodResponseWithDefaults instantiates a new GetPaymentMethodResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPaymentMethodResponseWithDefaults() *GetPaymentMethodResponse {
	this := GetPaymentMethodResponse{}
	return &this
}

// GetObject returns the Object field value
func (o *GetPaymentMethodResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *GetPaymentMethodResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *GetPaymentMethodResponse) SetObject(v string) {
	o.Object = v
}

// GetHasMore returns the HasMore field value
func (o *GetPaymentMethodResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *GetPaymentMethodResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *GetPaymentMethodResponse) SetHasMore(v bool) {
	o.HasMore = v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetPaymentMethodResponse) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.NextPageUrl.Get()
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPaymentMethodResponse) GetNextPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageUrl.Get(), o.NextPageUrl.IsSet()
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *GetPaymentMethodResponse) HasNextPageUrl() bool {
	if o != nil && o.NextPageUrl.IsSet() {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given NullableString and assigns it to the NextPageUrl field.
func (o *GetPaymentMethodResponse) SetNextPageUrl(v string) {
	o.NextPageUrl.Set(&v)
}
// SetNextPageUrlNil sets the value for NextPageUrl to be an explicit nil
func (o *GetPaymentMethodResponse) SetNextPageUrlNil() {
	o.NextPageUrl.Set(nil)
}

// UnsetNextPageUrl ensures that no value is present for NextPageUrl, not even an explicit nil
func (o *GetPaymentMethodResponse) UnsetNextPageUrl() {
	o.NextPageUrl.Unset()
}

// GetPreviousPageUrl returns the PreviousPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetPaymentMethodResponse) GetPreviousPageUrl() string {
	if o == nil || IsNil(o.PreviousPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PreviousPageUrl.Get()
}

// GetPreviousPageUrlOk returns a tuple with the PreviousPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetPaymentMethodResponse) GetPreviousPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousPageUrl.Get(), o.PreviousPageUrl.IsSet()
}

// HasPreviousPageUrl returns a boolean if a field has been set.
func (o *GetPaymentMethodResponse) HasPreviousPageUrl() bool {
	if o != nil && o.PreviousPageUrl.IsSet() {
		return true
	}

	return false
}

// SetPreviousPageUrl gets a reference to the given NullableString and assigns it to the PreviousPageUrl field.
func (o *GetPaymentMethodResponse) SetPreviousPageUrl(v string) {
	o.PreviousPageUrl.Set(&v)
}
// SetPreviousPageUrlNil sets the value for PreviousPageUrl to be an explicit nil
func (o *GetPaymentMethodResponse) SetPreviousPageUrlNil() {
	o.PreviousPageUrl.Set(nil)
}

// UnsetPreviousPageUrl ensures that no value is present for PreviousPageUrl, not even an explicit nil
func (o *GetPaymentMethodResponse) UnsetPreviousPageUrl() {
	o.PreviousPageUrl.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPaymentMethodResponse) GetData() []GetCustomerPaymentMethodDataResponse {
	if o == nil || IsNil(o.Data) {
		var ret []GetCustomerPaymentMethodDataResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPaymentMethodResponse) GetDataOk() ([]GetCustomerPaymentMethodDataResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPaymentMethodResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetCustomerPaymentMethodDataResponse and assigns it to the Data field.
func (o *GetPaymentMethodResponse) SetData(v []GetCustomerPaymentMethodDataResponse) {
	o.Data = v
}

func (o GetPaymentMethodResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPaymentMethodResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["has_more"] = o.HasMore
	if o.NextPageUrl.IsSet() {
		toSerialize["next_page_url"] = o.NextPageUrl.Get()
	}
	if o.PreviousPageUrl.IsSet() {
		toSerialize["previous_page_url"] = o.PreviousPageUrl.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetPaymentMethodResponse struct {
	value *GetPaymentMethodResponse
	isSet bool
}

func (v NullableGetPaymentMethodResponse) Get() *GetPaymentMethodResponse {
	return v.value
}

func (v *NullableGetPaymentMethodResponse) Set(val *GetPaymentMethodResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPaymentMethodResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPaymentMethodResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPaymentMethodResponse(val *GetPaymentMethodResponse) *NullableGetPaymentMethodResponse {
	return &NullableGetPaymentMethodResponse{value: val, isSet: true}
}

func (v NullableGetPaymentMethodResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPaymentMethodResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


