/*
Conekta API

Conekta sdk

API version: 2.1.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the ApiKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyRequest{}

// ApiKeyRequest struct for ApiKeyRequest
type ApiKeyRequest struct {
	// Indicates if the api key is active
	Active bool `json:"active"`
	// Detail of the use that will be given to the api key
	Description string `json:"description"`
	Role string `json:"role"`
}

// NewApiKeyRequest instantiates a new ApiKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyRequest(active bool, description string, role string) *ApiKeyRequest {
	this := ApiKeyRequest{}
	this.Active = active
	this.Description = description
	this.Role = role
	return &this
}

// NewApiKeyRequestWithDefaults instantiates a new ApiKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyRequestWithDefaults() *ApiKeyRequest {
	this := ApiKeyRequest{}
	return &this
}

// GetActive returns the Active field value
func (o *ApiKeyRequest) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ApiKeyRequest) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ApiKeyRequest) SetActive(v bool) {
	o.Active = v
}

// GetDescription returns the Description field value
func (o *ApiKeyRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ApiKeyRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ApiKeyRequest) SetDescription(v string) {
	o.Description = v
}

// GetRole returns the Role field value
func (o *ApiKeyRequest) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ApiKeyRequest) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ApiKeyRequest) SetRole(v string) {
	o.Role = v
}

func (o ApiKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active"] = o.Active
	toSerialize["description"] = o.Description
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

type NullableApiKeyRequest struct {
	value *ApiKeyRequest
	isSet bool
}

func (v NullableApiKeyRequest) Get() *ApiKeyRequest {
	return v.value
}

func (v *NullableApiKeyRequest) Set(val *ApiKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyRequest(val *ApiKeyRequest) *NullableApiKeyRequest {
	return &NullableApiKeyRequest{value: val, isSet: true}
}

func (v NullableApiKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


