/*
Conekta API

Conekta sdk

API version: 2.1.0
Contact: engineering@conekta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package conekta

import (
	"encoding/json"
)

// checks if the ChargeResponseRefundsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChargeResponseRefundsData{}

// ChargeResponseRefundsData struct for ChargeResponseRefundsData
type ChargeResponseRefundsData struct {
	Object string `json:"object"`
	Amount int64 `json:"amount"`
	Id string `json:"id"`
	CreatedAt int64 `json:"created_at"`
	AuthCode *string `json:"auth_code,omitempty"`
}

// NewChargeResponseRefundsData instantiates a new ChargeResponseRefundsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChargeResponseRefundsData(object string, amount int64, id string, createdAt int64) *ChargeResponseRefundsData {
	this := ChargeResponseRefundsData{}
	this.Object = object
	this.Amount = amount
	this.Id = id
	this.CreatedAt = createdAt
	return &this
}

// NewChargeResponseRefundsDataWithDefaults instantiates a new ChargeResponseRefundsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChargeResponseRefundsDataWithDefaults() *ChargeResponseRefundsData {
	this := ChargeResponseRefundsData{}
	return &this
}

// GetObject returns the Object field value
func (o *ChargeResponseRefundsData) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ChargeResponseRefundsData) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ChargeResponseRefundsData) SetObject(v string) {
	o.Object = v
}

// GetAmount returns the Amount field value
func (o *ChargeResponseRefundsData) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ChargeResponseRefundsData) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ChargeResponseRefundsData) SetAmount(v int64) {
	o.Amount = v
}

// GetId returns the Id field value
func (o *ChargeResponseRefundsData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChargeResponseRefundsData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChargeResponseRefundsData) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ChargeResponseRefundsData) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ChargeResponseRefundsData) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ChargeResponseRefundsData) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetAuthCode returns the AuthCode field value if set, zero value otherwise.
func (o *ChargeResponseRefundsData) GetAuthCode() string {
	if o == nil || IsNil(o.AuthCode) {
		var ret string
		return ret
	}
	return *o.AuthCode
}

// GetAuthCodeOk returns a tuple with the AuthCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargeResponseRefundsData) GetAuthCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthCode) {
		return nil, false
	}
	return o.AuthCode, true
}

// HasAuthCode returns a boolean if a field has been set.
func (o *ChargeResponseRefundsData) HasAuthCode() bool {
	if o != nil && !IsNil(o.AuthCode) {
		return true
	}

	return false
}

// SetAuthCode gets a reference to the given string and assigns it to the AuthCode field.
func (o *ChargeResponseRefundsData) SetAuthCode(v string) {
	o.AuthCode = &v
}

func (o ChargeResponseRefundsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChargeResponseRefundsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["amount"] = o.Amount
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.AuthCode) {
		toSerialize["auth_code"] = o.AuthCode
	}
	return toSerialize, nil
}

type NullableChargeResponseRefundsData struct {
	value *ChargeResponseRefundsData
	isSet bool
}

func (v NullableChargeResponseRefundsData) Get() *ChargeResponseRefundsData {
	return v.value
}

func (v *NullableChargeResponseRefundsData) Set(val *ChargeResponseRefundsData) {
	v.value = val
	v.isSet = true
}

func (v NullableChargeResponseRefundsData) IsSet() bool {
	return v.isSet
}

func (v *NullableChargeResponseRefundsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChargeResponseRefundsData(val *ChargeResponseRefundsData) *NullableChargeResponseRefundsData {
	return &NullableChargeResponseRefundsData{value: val, isSet: true}
}

func (v NullableChargeResponseRefundsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChargeResponseRefundsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


